version: '3.8'

services:
  api:
    build: .
    container_name: boce-api
    command: python -m app.cli api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always

  scheduler:
    build: .
    container_name: boce-scheduler
    command: python -m app.cli scheduler
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    depends_on:
      - api
